services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    environment:
      - FLASK_SERVER_PORT=8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
