services:
  backend:
    build:
      context: ./backend
      args:
        CERT: ${CERT}
        DATABASE_URL: ${DATABASE_URL}
      dockerfile: Dockerfile
    stop_signal: SIGINT
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - FLASK_SERVER_PORT=8000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
