services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    stop_signal: SIGINT
    ports:
      - '5000:5000'
    environment:
      - FLASK_SERVER_PORT=5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
