services:
  backend:
    build:
      context: backend
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    environment:
      - FLASK_SERVER_PORT=8000
    volumes:
      - ./backend:/src

  slackfrontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
